### ISSUE TITLE
Continuing the project?

### ISSUE THREAD

**Issue by fonty1** [rundmt/nifty-dm#6]
Hi @rundmt @teckliew, 

Just watched your showcase video and loved the concept. Wondering if you guys want to keep building?

What would be cool is if you replaced Firebase for the [Streamr Network](https://streamr.network/discover/network) - i.e. a decentralised pub/sub. Native Eth address chat is an ecosystem dApp we've especially wanted for a long time so it would be awesome to collaborate with you guys on that.

Let me know, we can support you with a [token grant](https://streamr.network/fund/).

**Comment by rundmt** [comment]
Hey @fonty1  we are planning to continue the project. We haven't done anything yet, but we do plan to rip out firebase as it was only for demo purposes. We'd love to evaluate Streamr Network. Feel free to reach out and email me derekmuoktor@gmail.com. I'll close out this issue.
